# Generated by Django 5.0.7 on 2024-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_guestlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guestlist", old_name="name", new_name="last_name",
        ),
        migrations.AddField(
            model_name="guestlist",
            name="hp_num",
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
